### PR TITLE
Added class for creating users

### PR DESCRIPTION
**Pull request by jpper**

### CODE REVIEW

**Comment by takafujimoto** [comment]
The RubyMine（JetBrain`s product） configuration file has been committed.
Please add it to gitignore and exclude it.

RubyMine（JetBrain社の製品）の設定ファイルがコミットされていますので
gitignoreに追加して除外するようにお願いします。

**Comment by jpper** [comment]
@takafujimoto Should be deleted. Is it okay that the files in bin are getting added to this, or should these be added to the .gitignore as well?

**Comment by takafujimoto** [comment]
getting added to this. 
it does not neet to .gitignore

**Comment by takafujimoto** [comment]
Please PR's comment described  summary of changes .
for example
https://github.com/sitateru/kpt/pull/20

**Pull request closed without merging**
